import type { Metadata } from "next";
{ /*import localFont from "next/font/local"; */ }
import {Inria_Sans} from "next/font/google"
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer"

const inria_Sans = Inria_Sans({
  weight: '400',
  subsets: ['latin'],
})

{ /*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/ }
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inria_Sans.className}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
